services:
  - type: web
    name: matching-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: matching-app-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.9.0

databases:
  - name: matching-app-db
    databaseName: matching_app
    user: matching_app_user
    plan: free 