services:
  - type: web
    name: matching-app-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn api.main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///./matching_app.db
    healthCheckPath: /docs
    autoDeploy: true

databases:
  - name: matching-app-db
    databaseName: matching_app
    user: matching_app_user
    plan: free 